--------------------------------------------------------
--  ÉtÉ@ÉCÉãÇçÏê¨ÇµÇ‹ÇµÇΩ - ì˙ójì˙-6åé-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "AIMAX"."USER_INFO" 
   (	"USER_ID" NUMBER(*,0), 
	"ACCOUNT_ID" VARCHAR2(128 BYTE), 
	"NAME_KANA_SEI" VARCHAR2(128 BYTE), 
	"NAME_KANA_MEI" VARCHAR2(128 BYTE), 
	"NAME_KANJI_SEI" VARCHAR2(128 BYTE), 
	"NAME_KANJI_MEI" VARCHAR2(128 BYTE), 
	"GENDER" NUMBER(*,0), 
	"BIRTHDAY" DATE, 
	"POSTALCODE" CHAR(8 BYTE), 
	"ADDRESS1" VARCHAR2(128 BYTE), 
	"ADDRESS2" VARCHAR2(128 BYTE), 
	"TEL_TYPE1" NUMBER(*,0), 
	"TEL_TYPE2" NUMBER(*,0), 
	"TEL_TYPE3" NUMBER(*,0), 
	"TEL_NUMBER1" VARCHAR2(16 BYTE), 
	"TEL_NUMBER2" VARCHAR2(16 BYTE), 
	"TEL_NUMBER3" VARCHAR2(16 BYTE), 
	"MAILADDRESS1" VARCHAR2(128 BYTE), 
	"MAILADDRESS2" VARCHAR2(128 BYTE), 
	"MAILADDRESS3" VARCHAR2(128 BYTE), 
	"COMPANY_TYPE" NUMBER(*,0), 
	"HIRE_DAY" DATE, 
	"LEAVING_DAY" DATE, 
	"STATUS_TYPE" NUMBER(*,0), 
	"COURTESY_REMAINING_CNT" NUMBER(*,0), 
	"ANNUAL_REMAINING_CNT" NUMBER(*,0), 
	"CREATED_DATE" VARCHAR2(10 BYTE), 
	"UPDATE_DATE" VARCHAR2(10 BYTE), 
	"DELETE_FLG" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006999
--------------------------------------------------------

  CREATE UNIQUE INDEX "AIMAX"."SYS_C006999" ON "AIMAX"."USER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_INFO
--------------------------------------------------------

  ALTER TABLE "AIMAX"."USER_INFO" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
